# one dimention array

In [1]:
pip install numpy

In [2]:
import numpy as np
a=np.array([5,5,5])
a

array([5, 5, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
len(a)

3

In [5]:
a[2]

5

In [6]:
a[0:]

array([5, 5, 5])

## two dimension array


In [7]:
# list of lists 

In [8]:
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
b[0]

array([5, 5, 5])

In [10]:
b[1:]

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
 import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [12]:
b=np.zeros(2)
b

array([0., 0.])

# create empty array with three  element 

In [13]:
d=np.empty(3)
d 

array([9.00966548e-312, 0.00000000e+000, 7.56587583e-307])

In [15]:
# with the rage of elements 
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [ ]:
b 