# Creating  array 

In [1]:
import numpy as np
food=np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [2]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [3]:
type(price)

numpy.ndarray

In [4]:
len(price)

3

In [5]:
len(food)

3

In [6]:
price[2 ]

5

In [7]:
  price[0:]    

array([5, 5, 5])

In [8]:
food[2]

'raita'

In [9]:
price.mean()

5.0

In [10]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [14]:
np.arange(3, 9999)

array([   3,    4,    5, ..., 9996, 9997, 9998])

In [15]:
np.arange(5, 20, 6)

array([ 5, 11, 17])

In [16]:
#table
np.arange(1, 50, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [17]:
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [18]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
#sorting 

In [20]:
a=np.array([10, 23, 34, 45, 56, 67, 78, 56])
a

array([10, 23, 34, 45, 56, 67, 78, 56])

In [21]:
a.sort()
a

array([10, 23, 34, 45, 56, 56, 67, 78])

In [22]:
b=np.array([10.2, 21.5, 43.4, 45.4, 44.4, 34.4])
b

array([10.2, 21.5, 43.4, 45.4, 44.4, 34.4])

In [23]:
b.sort()
b

array([10.2, 21.5, 34.4, 43.4, 44.4, 45.4])

In [24]:
c =np.concatenate((a,b))
c

array([10. , 23. , 34. , 45. , 56. , 56. , 67. , 78. , 10.2, 21.5, 34.4,
       43.4, 44.4, 45.4])

In [25]:
c.sort()
c

array([10. , 10.2, 21.5, 23. , 34. , 34.4, 43.4, 44.4, 45. , 45.4, 56. ,
       56. , 67. , 78. ])

#  two D array

In [26]:
import numpy as np

x = np.array([[2,3], [3,4,]])
x

array([[2, 3],
       [3, 4]])

In [27]:
y= np.array([[6,7],[8,9]])
y

array([[6, 7],
       [8, 9]])

In [28]:
np.concatenate((x,y), axis=0)   

array([[2, 3],
       [3, 4],
       [6, 7],
       [8, 9]])

In [29]:
np.concatenate((x,y), axis=1) 

array([[2, 3, 6, 7],
       [3, 4, 8, 9]])

In [34]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7]],
        
              [[0, 1, 2, 3],
               [4, 5, 6, 7]], 
         
              [[0, 1, 2, 3],
               [4, 5, 6, 7]]])
a


array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [35]:
# to find the no of dimensions 
a.ndim

3

In [36]:
b=np.array([[5, 6, 7],
           [8, 9, 10],
           [10, 11, 12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [38]:
b.ndim

2

In [39]:
# size of element 
a.size

24

In [41]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [40]:
a.shape

(3, 2, 4)

In [53]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
# reshape
b= a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
 #convert1 d  array into 2d array 

In [49]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a.shape

(9,)

In [52]:
b=a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
b.shape

(1, 9)

In [56]:
column wise
c=a[: ,np.newaxis]
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [58]:
a[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
a*9

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72])

In [60]:
a+9

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [62]:
a.sum()

36

In [63]:
a.mean()

4.0